version: "3.7"

services:
  react:
    build:
      context: .
    image: node:14.18.1-alpine
    container_name: react-app
    ports:
      - 3002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app/
      - /app/node_modules
    command: npm start
